spring:
  application:
    name: book-service
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/BookService
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/book-service
#            user-name-attribute: preferred_username
#        registration:
#          keycloak:
#            client-id: book-app
#            client-secret: ph0zOALGngz2GEWHy83A9dsPSJncpT9U
#            scope:
#              - openid
#              - view_catalogue
#              - edit_catalogue
#              -	microprofile-jwt
file:
  upload-dir: D:/uploads2B
#logging:
#  level:
#    org.springframework.security: trace
server:
  port: 8081
