spring:
  application:
    name: book-service
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/BookService
    username: postgres
    password: postgre
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
#  security:
#    user:
#      name: user
#      password: user
file:
  upload-dir: D:/uploads2B
logging:
  level:
    org.springframework.security: trace
